import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { Toaster } from "sonner";

const arimo = Arimo({
  variable: "--font-arimo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OLSUN",
  description: "Generated by OLSUN",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = await params;
  const messages = await getMessages();
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body
        className={`${arimo.variable}  antialiased custom-scrollbar-hidden`}
      >
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          {children}
          <Toaster position="top-center" richColors />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
